version: '2'

services:
    django:
        build:
            context: .
            dockerfile: Dockerfile
        volumes:
            - "./src:/app"
        environment:
            - PYTHONUNBUFFERED=0
            - PYTHONPYCACHEPREFIX=../__pycache__
        ports:
            - "8000:8000"
        command: python manage.py runserver 0.0.0.0:8000
        depends_on:
            - postgres

    postgres:
        image: postgres:13.2-alpine
        ports:
            - "5432:5432"
        volumes:
            - db:/var/lib/postgresql/data
        restart: always
        env_file:
            - .env
        environment:
            - POSTGRES_DB=${POSTGRES_DB}
            - POSTGRES_USER=${POSTGRES_USER}
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
            - POSTGRES_HOST=${POSTGRES_HOST}

volumes:
    db:
        driver: local

