# Generated by Django 4.1.5 on 2023-01-31 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shortened',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('original_url', models.URLField()),
                ('shortcode', models.CharField(max_length=10)),
                ('shortened_url', models.URLField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
